### ISSUE TITLE
Update 8

### ISSUE THREAD

**Issue by bazsy55** [keifufu/ProductionMultipliers#1]
The mod doesn't work in Update 8.

**Comment by keifufu** [comment]
Yeah, it's not been a priority to update this since I don't currently play satisfactory and don't want to bother with windows and setting up the development environment to be able to update it.

I don't know if I'd just have to recompile or if U8 changed something I'd have to fix either.

**Comment by bazsy55** [comment]
Thank you for your reply! 
I can try to update the mod to U8, but it's not clear how I can configure the development environment.

**Comment by keifufu** [comment]
The documentation is available at https://docs.ficsit.app
The modding discord is also very helpful: [the invite link from ficsit.app](https://discord.gg/xkVJ73E)

**Comment by bazsy55** [comment]
Thank you! I will close the issue now.
